CREATE TABLE IF NOT EXISTS project_payment_orders (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  project_id BIGINT UNSIGNED NOT NULL,
  payment_id BIGINT UNSIGNED NOT NULL,
  business_id BIGINT UNSIGNED NOT NULL,
  purpose ENUM('Escrow', 'Tip') NOT NULL,
  amount_paise BIGINT UNSIGNED NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'INR',
  provider VARCHAR(30) NOT NULL DEFAULT 'razorpay',
  provider_order_id VARCHAR(120) NOT NULL,
  provider_payment_id VARCHAR(120) NULL,
  provider_signature VARCHAR(255) NULL,
  note VARCHAR(255) NULL,
  status ENUM('Created', 'Paid', 'Failed') NOT NULL DEFAULT 'Created',
  paid_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT uq_payment_orders_provider_order UNIQUE (provider_order_id),
  CONSTRAINT fk_payment_orders_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_payment_orders_payment FOREIGN KEY (payment_id) REFERENCES project_payments(id) ON DELETE CASCADE,
  CONSTRAINT fk_payment_orders_business FOREIGN KEY (business_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_payment_orders_project_status (project_id, status),
  INDEX idx_payment_orders_business_created (business_id, created_at)
) ENGINE=InnoDB;
